networks:
  im-net:

services:
  im-etcd:
    container_name: im-etcd-server
    image: bitnami/etcd:3.5.17
    networks:
      - im-net
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_ADVERTISE_CLIENT_URLS=http://im-etcd-server:2379"
